/*
 * This file is generated by jOOQ.
 */
package com.redwolf.example.jooq.generator;


import com.redwolf.example.jooq.generator.tables.Device;
import com.redwolf.example.jooq.generator.tables.User;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>jooq_example</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index DEVICE_DEVICE_CODE_UINDEX = Indexes0.DEVICE_DEVICE_CODE_UINDEX;
    public static final Index DEVICE_DEVICE_NAME_UINDEX = Indexes0.DEVICE_DEVICE_NAME_UINDEX;
    public static final Index DEVICE_PRIMARY = Indexes0.DEVICE_PRIMARY;
    public static final Index USER_PRIMARY = Indexes0.USER_PRIMARY;
    public static final Index USER_USER_PHONE_UINDEX = Indexes0.USER_USER_PHONE_UINDEX;
    public static final Index USER_USER_USERNAME_UINDEX = Indexes0.USER_USER_USERNAME_UINDEX;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index DEVICE_DEVICE_CODE_UINDEX = Internal.createIndex("device_code_uindex", Device.DEVICE, new OrderField[] { Device.DEVICE.CODE }, true);
        public static Index DEVICE_DEVICE_NAME_UINDEX = Internal.createIndex("device_name_uindex", Device.DEVICE, new OrderField[] { Device.DEVICE.NAME }, true);
        public static Index DEVICE_PRIMARY = Internal.createIndex("PRIMARY", Device.DEVICE, new OrderField[] { Device.DEVICE.ID }, true);
        public static Index USER_PRIMARY = Internal.createIndex("PRIMARY", User.USER, new OrderField[] { User.USER.ID }, true);
        public static Index USER_USER_PHONE_UINDEX = Internal.createIndex("user_phone_uindex", User.USER, new OrderField[] { User.USER.PHONE }, true);
        public static Index USER_USER_USERNAME_UINDEX = Internal.createIndex("user_username_uindex", User.USER, new OrderField[] { User.USER.USERNAME }, true);
    }
}
