/*
 * This file is generated by jOOQ.
 */
package com.redwolf.example.jooq.generator;


import com.redwolf.example.jooq.generator.tables.Device;
import com.redwolf.example.jooq.generator.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqExample extends SchemaImpl {

    private static final long serialVersionUID = -1603265242;

    /**
     * The reference instance of <code>jooq_example</code>
     */
    public static final JooqExample JOOQ_EXAMPLE = new JooqExample();

    /**
     * The table <code>jooq_example.device</code>.
     */
    public final Device DEVICE = com.redwolf.example.jooq.generator.tables.Device.DEVICE;

    /**
     * The table <code>jooq_example.user</code>.
     */
    public final User USER = com.redwolf.example.jooq.generator.tables.User.USER;

    /**
     * No further instances allowed
     */
    private JooqExample() {
        super("jooq_example", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Device.DEVICE,
            User.USER);
    }
}
