/*
 * This file is generated by jOOQ.
 */
package com.redwolf.example.jooq.generator;


import com.redwolf.example.jooq.generator.tables.Device;
import com.redwolf.example.jooq.generator.tables.User;
import com.redwolf.example.jooq.generator.tables.records.DeviceRecord;
import com.redwolf.example.jooq.generator.tables.records.UserRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>jooq_example</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<UserRecord, Long> IDENTITY_USER = Identities0.IDENTITY_USER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DeviceRecord> KEY_DEVICE_PRIMARY = UniqueKeys0.KEY_DEVICE_PRIMARY;
    public static final UniqueKey<DeviceRecord> KEY_DEVICE_DEVICE_CODE_UINDEX = UniqueKeys0.KEY_DEVICE_DEVICE_CODE_UINDEX;
    public static final UniqueKey<DeviceRecord> KEY_DEVICE_DEVICE_NAME_UINDEX = UniqueKeys0.KEY_DEVICE_DEVICE_NAME_UINDEX;
    public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = UniqueKeys0.KEY_USER_PRIMARY;
    public static final UniqueKey<UserRecord> KEY_USER_USER_USERNAME_UINDEX = UniqueKeys0.KEY_USER_USER_USERNAME_UINDEX;
    public static final UniqueKey<UserRecord> KEY_USER_USER_PHONE_UINDEX = UniqueKeys0.KEY_USER_USER_PHONE_UINDEX;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<UserRecord, Long> IDENTITY_USER = Internal.createIdentity(User.USER, User.USER.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<DeviceRecord> KEY_DEVICE_PRIMARY = Internal.createUniqueKey(Device.DEVICE, "KEY_device_PRIMARY", Device.DEVICE.ID);
        public static final UniqueKey<DeviceRecord> KEY_DEVICE_DEVICE_CODE_UINDEX = Internal.createUniqueKey(Device.DEVICE, "KEY_device_device_code_uindex", Device.DEVICE.CODE);
        public static final UniqueKey<DeviceRecord> KEY_DEVICE_DEVICE_NAME_UINDEX = Internal.createUniqueKey(Device.DEVICE, "KEY_device_device_name_uindex", Device.DEVICE.NAME);
        public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = Internal.createUniqueKey(User.USER, "KEY_user_PRIMARY", User.USER.ID);
        public static final UniqueKey<UserRecord> KEY_USER_USER_USERNAME_UINDEX = Internal.createUniqueKey(User.USER, "KEY_user_user_username_uindex", User.USER.USERNAME);
        public static final UniqueKey<UserRecord> KEY_USER_USER_PHONE_UINDEX = Internal.createUniqueKey(User.USER, "KEY_user_user_phone_uindex", User.USER.PHONE);
    }
}
