/*
 * This file is generated by jOOQ.
 */
package com.redwolf.example.jooq.generator;


import com.redwolf.example.jooq.generator.tables.Device;
import com.redwolf.example.jooq.generator.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in jooq_example
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jooq_example.device</code>.
     */
    public static final Device DEVICE = com.redwolf.example.jooq.generator.tables.Device.DEVICE;

    /**
     * The table <code>jooq_example.user</code>.
     */
    public static final User USER = com.redwolf.example.jooq.generator.tables.User.USER;
}
