/*
 * This file is generated by jOOQ.
 */
package com.redwolf.example.jooq.generator.tables;


import com.redwolf.example.jooq.generator.Indexes;
import com.redwolf.example.jooq.generator.JooqExample;
import com.redwolf.example.jooq.generator.Keys;
import com.redwolf.example.jooq.generator.tables.records.DeviceRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Device extends TableImpl<DeviceRecord> {

    private static final long serialVersionUID = 15968611;

    /**
     * The reference instance of <code>jooq_example.device</code>
     */
    public static final Device DEVICE = new Device();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DeviceRecord> getRecordType() {
        return DeviceRecord.class;
    }

    /**
     * The column <code>jooq_example.device.id</code>.
     */
    public final TableField<DeviceRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>jooq_example.device.code</code>.
     */
    public final TableField<DeviceRecord, String> CODE = createField("code", org.jooq.impl.SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>jooq_example.device.name</code>.
     */
    public final TableField<DeviceRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>jooq_example.device.description</code>.
     */
    public final TableField<DeviceRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * Create a <code>jooq_example.device</code> table reference
     */
    public Device() {
        this(DSL.name("device"), null);
    }

    /**
     * Create an aliased <code>jooq_example.device</code> table reference
     */
    public Device(String alias) {
        this(DSL.name(alias), DEVICE);
    }

    /**
     * Create an aliased <code>jooq_example.device</code> table reference
     */
    public Device(Name alias) {
        this(alias, DEVICE);
    }

    private Device(Name alias, Table<DeviceRecord> aliased) {
        this(alias, aliased, null);
    }

    private Device(Name alias, Table<DeviceRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Device(Table<O> child, ForeignKey<O, DeviceRecord> key) {
        super(child, key, DEVICE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return JooqExample.JOOQ_EXAMPLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.DEVICE_DEVICE_CODE_UINDEX, Indexes.DEVICE_DEVICE_NAME_UINDEX, Indexes.DEVICE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DeviceRecord> getPrimaryKey() {
        return Keys.KEY_DEVICE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DeviceRecord>> getKeys() {
        return Arrays.<UniqueKey<DeviceRecord>>asList(Keys.KEY_DEVICE_PRIMARY, Keys.KEY_DEVICE_DEVICE_CODE_UINDEX, Keys.KEY_DEVICE_DEVICE_NAME_UINDEX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Device as(String alias) {
        return new Device(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Device as(Name alias) {
        return new Device(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Device rename(String name) {
        return new Device(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Device rename(Name name) {
        return new Device(name, null);
    }
}
